version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - yarn install
  build:
    commands:
      - yarn build

artifacts:
  base-directory: build
  files:
    - "**/*"
