version: "3.9"
services:
  node-express:
    build: .
    container_name: node-express
    env_file:
      - .env
    ports:
      - 5544:4433
    restart: always
# docker build -t node:latest .
# docker run -p -e -e --name -d node:latest