name: Docker Image CI

on:
  push:
    branches: ["github-action-ec2"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Docker login
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${DOCKER_USERNAME}/simple-express-app

      - name: Push Image to Docker Hub
        run: docker push ${DOCKER_USERNAME}/simple-express-app:latest
